name: asw
favicon: null
layout_spectrum: 0.86105
typography_spectrum: 0.46985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#34672c'
    - '#000000'
    - '#fbca02'
    - '#c04794'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
