name: asw
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3e2ae'
    - '#457448'
    - '#ffffff'
    - '#5f8762'
    - '#a3b9a4'
  brandStrength: 0.3125
  lightness: 0.7313279791269451
  saturation: 0.5474406718276441
  rhythmicContrast: 0.5672622125130147
purpose: []
